spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.cfg.EJB3NamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HANAColumnStoreDialect
        jdbc:
          lob:
            non_contextual_creation: true


hana:
  url: ${vcap.services.spring.credentials.url}
  user: ${vcap.services.spring.credentials.user}
  password: ${vcap.services.spring.credentials.password}


